import Head from 'next/head'
import { useState } from 'react'
import { useReward } from 'react-rewards';

export default function Home() {
  const [count, setCount] = useState(0)
  const { reward, isAnimating } = useReward('rewardId', 'confetti');
  return (
    <>
      <Head>
        <title>Next.js App</title>
        <meta name="description" content="generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-col justify-center items-center h-screen'>
        <div className='text-4xl mb-4'>CLICK</div>
        <button className='btn btn-outline w-16 text-xl' onClick={() => {
          setCount(count + 1);
          if ((count + 1) % 10 === 0) {
            reward();
          }
        }}>{count}
          <span id="rewardId" /></button>
      </div>

    </>
  )
}
